export var eventsMap = {
    'abort': 'abort',
    'after print': 'afterprint',
    'animation end': 'animationend',
    'animation iteration': 'animationiteration',
    'animation start': 'animationstart',
    'audio process': 'audioprocess',
    'before print': 'beforeprint ',
    'before unload': 'beforeunload',
    'begin event': 'beginEvent',
    'blocked': 'blocked',
    'blur': 'blur',
    'cached': 'cached',
    'can play': 'canplay',
    'can play through': 'canplaythrough',
    'change': 'change',
    'charging change': 'chargingchange',
    'charging time change': 'chargingtimechange',
    'checking': 'checking',
    'click': 'click',
    'close': 'close',
    'complete': 'complete',
    'composition end': 'compositionend',
    'composition start': 'compositionstart',
    'composition update': 'compositionupdate',
    'context menu': 'contextmenu',
    'copy': 'copy',
    'cut': 'cut',
    'double click': 'dblclick',
    'device light': 'devicelight',
    'device motion': 'devicemotion',
    'device orientation': 'deviceorientation',
    'device proximity': 'deviceproximity',
    'discharging time change': 'dischargingtimechange',
    'dom activate': 'DOMActivate',
    'dom attr modified': 'DOMAttrModified  ',
    'dom character data modified': 'DOMCharacterDataModified  ',
    'dom content loaded': 'DOMContentLoaded',
    'downloading': 'downloading',
    'drag': 'drag',
    'drag end': 'dragend',
    'drag enter': 'dragenter',
    'drag leave': 'dragleave',
    'drag over': 'dragover',
    'drag start': 'dragstart',
    'drop': 'drop',
    'duration change': 'durationchange',
    'emptied': 'emptied',
    'ended': 'ended',
    'end event': 'endEvent',
    'error': 'error',
    'focus': 'focus',
    'fullscreen change': 'fullscreenchange',
    'fullscreen error': 'fullscreenerror',
    'gamepad connected': 'gamepadconnected',
    'gamepad disconnected': 'gamepaddisconnected',
    'hash change': 'hashchange',
    'input': 'input',
    'invalid': 'invalid',
    'keydown': 'keydown',
    'keypress': 'keypress',
    'keyup': 'keyup',
    'language change': 'languagechange',
    'level change': 'levelchange',
    'load': 'load',
    'loaded data': 'loadeddata',
    'loaded metadata': 'loadedmetadata',
    'load end': 'loadend',
    'load start': 'loadstart',
    'message': 'message',
    'mouse down': 'mousedown',
    'mouse enter': 'mouseenter',
    'mouse leave': 'mouseleave',
    'mouse move': 'mousemove',
    'mouse out': 'mouseout',
    'mouse over': 'mouseover',
    'mouse up': 'mouseup',
    'no update': 'noupdate',
    'obsolete': 'obsolete',
    'offline': 'offline',
    'online': 'online',
    'open': 'open',
    'orientation change': 'orientationchange',
    'page hide': 'pagehide',
    'pageshow': 'pageshow',
    'paste': 'paste',
    'pause': 'pause',
    'pointer lock change': 'pointerlockchange',
    'pointer lock error': 'pointerlockerror',
    'play': 'play',
    'playing': 'playing',
    'popstate': 'popstate',
    'progress': 'progress',
    'rate change': 'ratechange',
    'ready state change': 'readystatechange',
    'repeat event': 'repeatEvent',
    'reset': 'reset',
    'resize': 'resize',
    'scroll': 'scroll',
    'seeked': 'seeked',
    'seeking': 'seeking',
    'select': 'select',
    'show': 'show',
    'stalled': 'stalled',
    'storage': 'storage',
    'submit': 'submit',
    'success': 'success',
    'suspend': 'suspend',
    'svg abort': 'SVGAbort',
    'svg rror': 'SVGError',
    'svg load': 'SVGLoad',
    'svg resize': 'SVGResize',
    'svg croll': 'SVGScroll',
    'svg unload': 'SVGUnload',
    'svg zoom': 'SVGZoom',
    'timeout': 'timeout',
    'time update': 'timeupdate',
    'touch cancel': 'touchcancel',
    'touch end': 'touchend',
    'touch enter': 'touchenter',
    'touch leave': 'touchleave',
    'touch move': 'touchmove',
    'touch start': 'touchstart',
    'transition end': 'transitionend',
    'unload': 'unload',
    'update ready': 'updateready',
    'upgrade needed': 'upgradeneeded',
    'user proximity': 'userproximity',
    'version change': 'versionchange',
    'visibility change': 'visibilitychange',
    'volume change': 'volumechange',
    'waiting': 'waiting',
    'wheel': 'wheel'
};
