export var eventsMap = {
    'abort': 'abort',
    'after print': 'afterprint',
    'animation end': 'animationend',
    'animation iteration': 'animationiteration',
    'animation start': 'animationstart',
    'audio process': 'audioprocess',
    'before print': 'beforeprint ',
    'before unload': 'beforeunload',
    'begin event': 'beginEvent',
    'blocked': 'blocked',
    'blur': 'blur',
    'cached': 'cached',
    'can play': 'canplay',
    'can play through': 'canplaythrough',
    'change': 'change',
    'charging change': 'chargingchange',
    'charging time change': 'chargingtimechange',
    'checking': 'checking',
    'click': 'click',
    'close': 'close',
    'complete': 'complete',
    'composition end': 'compositionend',
    'composition start': 'compositionstart',
    'composition update': 'compositionupdate',
    'context menu': 'contextmenu',
    'copy': 'copy',
    'cut': 'cut',
    'double click': 'dblclick',
    'device light': 'devicelight',
    'device motion': 'devicemotion',
    'device orientation': 'deviceorientation',
    'device proximity': 'deviceproximity',
    'discharging time change': 'dischargingtimechange',
    'dom activate': 'DOMActivate  ',
    'dom attribute name changed': 'DOMAttributeNameChanged',
    'dom attr modified': 'DOMAttrModified  ',
    'dom character data modified': 'DOMCharacterDataModified  ',
    'dom content loaded': 'DOMContentLoaded',
    'dom element name changed': 'DOMElementNameChanged  ',
    'dom focus in': 'DOMFocusIn',
    'dom focus out': 'DOMFocusOut',
    'dom node inserted': 'DOMNodeInserted',
    'dom node inserted into document': 'DOMNodeInsertedIntoDocument',
    'dom node removed': 'DOMNodeRemoved',
    'dom node removed from document': 'DOMNodeRemovedFromDocument',
    'dom subtree modified': 'DOMSubtreeModified',
    'downloading': 'downloading',
    'drag': 'drag',
    'drag end': 'dragend',
    'drag enter': 'dragenter',
    'drag leave': 'dragleave',
    'drag over': 'dragover',
    'drag start': 'dragstart',
    'drop': 'drop',
    'duration change': 'durationchange',
    'emptied': 'emptied',
    'ended': 'ended',
    'end event': 'endEvent',
    'error': 'error',
    'focus': 'focus',
    'focus in': 'focusin',
    'focus out': 'focusout',
    'fullscreen change': 'fullscreenchange',
    'fullscreen error': 'fullscreenerror',
    'gamepad connected': 'gamepadconnected',
    'gamepad disconnected': 'gamepaddisconnected',
    'hash change': 'hashchange',
    'input': 'input',
    'invalid': 'invalid',
    'keydown': 'keydown',
    'keypress': 'keypress',
    'keyup': 'keyup',
    'language change': 'languagechange',
    'level change': 'levelchange',
    'load': 'load',
    'loaded data': 'loadeddata',
    'loaded metadata': 'loadedmetadata',
    'load end': 'loadend',
    'load start': 'loadstart',
    'message': 'message',
    'mouse down': 'mousedown',
    'mouse enter': 'mouseenter',
    'mouse leave': 'mouseleave',
    'mouse move': 'mousemove',
    'mouse out': 'mouseout',
    'mouse over': 'mouseover',
    'mouse up': 'mouseup',
    'no update': 'noupdate',
    'obsolete': 'obsolete',
    'offline': 'offline',
    'online': 'online',
    'open': 'open',
    'orientation change': 'orientationchange',
    'page hide': 'pagehide',
    'pageshow': 'pageshow',
    'paste': 'paste',
    'pause': 'pause',
    'pointer lock change': 'pointerlockchange',
    'pointer lock error': 'pointerlockerror',
    'play': 'play',
    'playing': 'playing',
    'popstate': 'popstate',
    'progress': 'progress',
    'rate change': 'ratechange',
    'ready state change': 'readystatechange',
    'repeat event': 'repeatEvent',
    'reset': 'reset',
    'resize': 'resize',
    'scroll': 'scroll',
    'seeked': 'seeked',
    'seeking': 'seeking',
    'select': 'select',
    'show': 'show',
    'stalled': 'stalled',
    'storage': 'storage',
    'submit': 'submit',
    'success': 'success',
    'suspend': 'suspend',
    'svg abort': 'SVGAbort',
    'svg rror': 'SVGError',
    'svg load': 'SVGLoad',
    'svg resize': 'SVGResize',
    'svg croll': 'SVGScroll',
    'svg unload': 'SVGUnload',
    'svg zoom': 'SVGZoom',
    'timeout': 'timeout',
    'time update': 'timeupdate',
    'touch cancel': 'touchcancel',
    'touch end': 'touchend',
    'touch enter': 'touchenter',
    'touch leave': 'touchleave',
    'touch move': 'touchmove',
    'touch start': 'touchstart',
    'transition end': 'transitionend',
    'unload': 'unload',
    'update ready': 'updateready',
    'upgrade needed': 'upgradeneeded',
    'user proximity': 'userproximity',
    'version change': 'versionchange',
    'visibility change': 'visibilitychange',
    'volume change': 'volumechange',
    'waiting': 'waiting',
    'wheel': 'wheel',
    'after script execute': 'afterscriptexecute',
    'before script execute': 'beforescriptexecute',
    'card state change': 'cardstatechange',
    'connection info update': 'connectionInfoUpdate',
    'cf state change': 'cfstatechange',
    'data change': 'datachange',
    'data error': 'dataerror',
    'dom mouse scroll': 'DOMMouseScroll',
    'drag drop': 'dragdrop',
    'drag exit': 'dragexit',
    'drag gesture': 'draggesture',
    'icc card lock error': 'icccardlockerror',
    'icc info change': 'iccinfochange',
    'localized': 'localized',
    'alerting': 'alerting',
    'busy': 'busy',
    'calls changed': 'callschanged',
    'connected': 'connected',
    'connecting': 'connecting',
    'delivered': 'delivered',
    'dialing': 'dialing',
    'disabled': 'disabled',
    'disconnected': 'disconnected',
    'disconnecting': 'disconnecting',
    'enabled': 'enabled',
    'held': 'held',
    'holding': 'holding',
    'incoming': 'incoming',
    'received': 'received',
    'resuming': 'resuming',
    'sent': 'sent',
    'state change': 'statechange',
    'status change': 'statuschange',
    'overflow': 'overflow',
    'smartcard insert': 'smartcard-insert',
    'smartcard remove': 'smartcard-remove',
    'stk command': 'stkcommand',
    'stk session end': 'stksessionend',
    'text': 'text',
    'under flow': 'underflow',
    'upload progress': 'uploadprogress  ',
    'ussd received': 'ussdreceived',
    'voice change': 'voicechange',
    'broadcast': 'broadcast',
    'checkbox state change': 'CheckboxStateChange',
    'command': 'command',
    'command update': 'commandupdate',
    'dom menu item active': 'DOMMenuItemActive',
    'dom menu item inactive': 'DOMMenuItemInactive',
    'popup hidden': 'popuphidden',
    'popup hiding': 'popuphiding',
    'popup showing': 'popupshowing',
    'popup shown': 'popupshown',
    'radio state change': 'RadioStateChange',
    'value change': 'ValueChange',
    'dom popup blocked': 'DOMPopupBlocked',
    'dom window created': 'DOMWindowCreated',
    'dom window close': 'DOMWindowClose',
    'dom title changed': 'DOMTitleChanged',
    'dom link added': 'DOMLinkAdded',
    'dom link removed': 'DOMLinkRemoved',
    'dom meta added': 'DOMMetaAdded',
    'dom meta removed': 'DOMMetaRemoved',
    'dom will open modal dialog': 'DOMWillOpenModalDialog',
    'dom modal dialog closed': 'DOMModalDialogClosed',
    'dom auto complete': 'DOMAutoComplete',
    'dom frame content loaded': 'DOMFrameContentLoaded',
    'alert active': 'AlertActive',
    'alert close': 'AlertClose',
    'full screen': 'fullscreen',
    'size mode change': 'sizemodechange',
    'ss window closing': 'SSWindowClosing',
    'ss tab closing': 'SSTabClosing',
    'ss tab restoring': 'SSTabRestoring',
    'ss tab restored': 'SSTabRestored',
    'ss window state ready': 'SSWindowStateReady',
    'ss window state busy': 'SSWindowStateBusy',
    'tab view search enabled': 'tabviewsearchenabled',
    'tab view search disabled': 'tabviewsearchdisabled',
    'tab view frame initialized': 'tabviewframeinitialized',
    'tab view shown': 'tabviewshown',
    'tab view hidden': 'tabviewhidden',
    'tab open': 'TabOpen',
    'tab close': 'TabClose',
    'tab select': 'TabSelect',
    'tab show': 'TabShow',
    'tab hide': 'TabHide',
    'tab pinned': 'TabPinned',
    'tab unpinned': 'TabUnpinned',
    'css rule view refreshed': 'CssRuleViewRefreshed',
    'css rule view changed': 'CssRuleViewChanged',
    'css rule view css link clicked': 'CssRuleViewCSSLinkClicked'
};
