language: node_js
node_js:
  - "0.12.4"
before_install:
  - npm -g install testem
  - npm -g install gulp
env:
  - DISPLAY=:99.0
before_script:
  - sh -e /etc/init.d/xvfb start
  - sleep 3
addons:
  firefox: "38.0"
